name = "ScanByte"
uuid = "7b38b023-a4d7-4c5e-8d43-3f3097f304eb"
authors = ["Jakob Nybo Nissen <jakobnybonissen@gmail.com>"]
version = "0.2.0"

[deps]
Libdl = "8f399da3-3557-5675-b5ff-fb832c97cbdb"
SIMD = "fdea26ae-647d-5447-a871-4b548cad5224"

[compat]
julia = "1.5"
SIMD = "3"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
